create table blog (id bigint not null auto_increment, content_id bigint, content_snippet longtext, entry_content longtext, entry_name varchar(255), milliseconds datetime, creator_id bigint, primary key (id)) engine=InnoDB;
create table blog_category (blog_id bigint not null, category varchar(255)) engine=InnoDB;
create table content (id bigint not null auto_increment, category varchar(255), content_file varchar(255), content_title varchar(255), content_url varchar(255), description longtext, image_file longblob, on_front_page bit, license_id bigint, primary key (id)) engine=InnoDB;
create table content_creator (content_id bigint not null, creator_id bigint not null, primary key (content_id, creator_id)) engine=InnoDB;
create table content_model (content_id bigint not null, model_id bigint not null, primary key (content_id, model_id)) engine=InnoDB;
create table content_tags (content_id bigint not null, tags_id bigint not null, primary key (content_id, tags_id)) engine=InnoDB;
create table creator (id bigint not null auto_increment, description longtext, name varchar(255), primary key (id)) engine=InnoDB;
create table gallery (id bigint not null auto_increment, description varchar(255), gallery_title varchar(255), is_featured bit, primary key (id)) engine=InnoDB;
create table gallery_content (gallery_id bigint not null, content_id bigint not null) engine=InnoDB;
create table license (id bigint not null auto_increment, category varchar(255), short_description longtext, url varchar(255), primary key (id)) engine=InnoDB;
create table model (id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table project (id bigint not null auto_increment, description longtext, name varchar(255), project_category varchar(255), primary key (id)) engine=InnoDB;
create table project_blog (project_id bigint not null, blog_id bigint not null, primary key (project_id, blog_id)) engine=InnoDB;
create table project_creator (project_id bigint not null, creator_id bigint not null, primary key (project_id, creator_id)) engine=InnoDB;
create table project_gallery (project_id bigint not null, gallery_id bigint not null, primary key (project_id, gallery_id)) engine=InnoDB;
create table project_tags (project_id bigint not null, tags_id bigint not null, primary key (project_id, tags_id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, tag varchar(255), primary key (id)) engine=InnoDB;
alter table project_blog add constraint UK_577gn33d33h2noqano3uuo8ih unique (blog_id);
alter table project_creator add constraint UK_acrvu3pqualj7085rg1p70c7d unique (creator_id);
alter table project_gallery add constraint UK_kkeo3bqqdk87im3lo2j1xh7hl unique (gallery_id);
alter table blog add constraint FK7em9v771ne1ha6cwiiumbscce foreign key (creator_id) references creator (id);
alter table blog_category add constraint FKd9e03c7wlyfdv7dd51bvnxc4x foreign key (blog_id) references blog (id);
alter table content add constraint FKavdloaf8nekyc0d035cprvlax foreign key (license_id) references license (id);
alter table content_creator add constraint FK79nb2akjdwrxbxavs8e9ae9he foreign key (creator_id) references creator (id);
alter table content_creator add constraint FK2p2jw0wlyjt113d86pdgqc8i4 foreign key (content_id) references content (id);
alter table content_model add constraint FK39syr7neb0jvu684noxwfibkt foreign key (model_id) references model (id);
alter table content_model add constraint FK13xmk2iuexls1qjoaiynfnwfk foreign key (content_id) references content (id);
alter table content_tags add constraint FKgus01gseane0hhgt10iqi7qk7 foreign key (tags_id) references tag (id);
alter table content_tags add constraint FKk2kryxst26wv9c14q7s1lt5fq foreign key (content_id) references content (id);
alter table gallery_content add constraint FK16jm74iypndgi59r5uo3bepjc foreign key (content_id) references content (id);
alter table gallery_content add constraint FKlehpe05hms5j2wj74fawh1do1 foreign key (gallery_id) references gallery (id);
alter table project_blog add constraint FKstnuxmo8viq6w3g49qp6koblk foreign key (blog_id) references blog (id);
alter table project_blog add constraint FK54jtbgewc1lvx7dtsv28crjh6 foreign key (project_id) references project (id);
alter table project_creator add constraint FK5amclccwq7q11d81u6g35j5cf foreign key (creator_id) references creator (id);
alter table project_creator add constraint FKpsiq7bw4npy3ugkwelrhvgrrr foreign key (project_id) references project (id);
alter table project_gallery add constraint FKtkbcr3afqbmn98orl6osxgotr foreign key (gallery_id) references gallery (id);
alter table project_gallery add constraint FKn1pr9fyq6or8scfge9to2brkx foreign key (project_id) references project (id);
alter table project_tags add constraint FKl7ukpu2t0cd2rlc8bl5o7igtw foreign key (tags_id) references tag (id);
alter table project_tags add constraint FKfvy64usu7e9x7ev6obh91q0qe foreign key (project_id) references project (id);
