version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  slack: circleci/slack@3.4.2

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - slack/approval-notification:
          message: Pending approval
          webhook: webhook